# icapsuricata configuration

# Load the module
Service suricata_service srv_suricata.so

# Protocol mode: allow204|disallow204, defaults to allow204
# suricata.Mode disallow204

# ACK window size: 0-65535, defaults to 4000
# Setting to 0 disables ACK flushes in IDS mode
# icapsuricata will not start if ACKwindow is specified in IPS mode
suricata.ACKwindow 4000

# Preview size: 0-65535, defaults to 65535, max size allowed
suricata.Preview 1024

# Buffer size: from preview size to 4194304, defaults to 65535, max preview size
# icapsuricata will not start if the buffer size is smaller than the preview size
# Note that c-icap's read and write buffer sizes are 4096 by default
suricata.BufSize 4096
